// frontend/src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      {/* ✅ Developer Fix: suppressHydrationWarning যুক্ত করা হয়েছে। 
        এতে Grammarly বা অন্য কোনো এক্সটেনশন <body> ট্যাগে এক্সট্রা কিছু বসালে 
        Next.js আর এরর থ্রো করবে না। 
      */}
      <body className="font-sans min-h-full flex flex-col" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}